export default {
	start: 'Start',
	'start.welcome': 'Welcome, World!',
	'start.newProject': 'Start a new project',
	'start.config': 'Configuration',
	'start.migrate': 'Migrate to Astro',

	guides: 'Guides and Recipes',
	'guides.routing': 'Routing and Navigation',
	'guides.ui': 'Build your UI',
	'guides.content': 'Add content to your site',
	'guides.serverRendering': 'Server rendering',
	'guides.upgrade': 'Upgrade',
	'guides.upgrade.major': 'Major upgrade guides',
	'guides.recipes': 'How-to recipes',

	reference: 'Reference',
	'reference.configuration': 'Configuration',
	'reference.runtime': 'Runtime API',
	'reference.cli': 'CLI',
	'reference.errors': 'Errors',
	'reference.errors.messages': 'Error messages',
	'reference.other': 'Other development APIs',

	integrations: 'Integrations',
	'integrations.ui': 'UI frameworks',
	'integrations.adapters': 'Adapters',
	'integrations.other': 'Other official integrations',

	thirdParty: 'Third-party services',
	'thirdParty.deployment': 'Deployment guides',
	'thirdParty.cms': 'Content management systems',
	'thirdParty.backend': 'Backend services',
	'thirdParty.media': 'Hosted media & DAM',
};
