# See https://github.com/actions/labeler

'🚨 action':
  - changed-files:
      - all-globs-to-any-file: [.github/workflows/**]

# Note: The "any" logic requires ANY file of the PR to match ALL (!) of the globs in the array,
# so to match files in multiple different paths, we also need multiple "any" arrays.
i18n:
  - changed-files:
      - all-globs-to-any-file: ['src/content/docs/**/*.mdx', '!src/content/docs/en/**/*']
  - changed-files:
      - all-globs-to-any-file: ['src/content/i18n/*', '!src/content/i18n/en.yml']
  - changed-files:
      - all-globs-to-any-file: ['src/content/nav/*', '!src/content/nav/en.ts']
  - changed-files:
      - all-globs-to-any-file: ['i18n-guides/*']
