peerDependencyRules:
  # Suppress warnings about these peer dependencies which we don’t need.
  ignoreMissing:
    - '@types/react'
    - 'react'
    - 'react-dom'
    - 'vite'

# Wait 3 days before permitting newly published packages to be installed. This helps protect against
# compromised packages that with any luck will be detected and removed within 3 days.
minimumReleaseAge: 4320

# We don’t need to run these build scripts, so explicitly disallow them as a minor security measure.
allowBuilds:
  esbuild: false
  sharp: false
  workerd: true
