name: "Incorrect Content Report 📄"
description: Report a correction to docs.
labels: [
  "improve or update documentation"
]
body:
  - type: markdown
    attributes:
      value: "# Reminder: If reporting a minor correction (e.g. typo), feel free to submit a PR directly!"
  - type: input
    id: subject
    attributes:
      label: 📚 Subject area/topic
      description: Documentation area/topic (e.g. SSR, CMS guide, environment variables)
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: page
    attributes:
      label: "📋 Page(s) affected (or suggested, for new content)"
      description: Please provide the URL of the page(s) affected.
      placeholder: https://docs.astro.build/en/getting-started/
    validations:
        required: true
  - type: textarea
    id: generalDesc
    attributes:
      label: "📋 Description of content that is out-of-date or incorrect"
      description: Let us know what's wrong!
      placeholder: "..."
    validations:
        required: true
  - type: textarea
    id: incorrectContent
    attributes:
      label: "🖥️ Reproduction in StackBlitz (if reporting incorrect content or code samples)"
      description: If you are reporting incorrect content or code samples, you can also attach a reproduction in stackblitz. See https://astro.new for starter projects.
      placeholder: "..."
    validations:
        required: false
