name: Install Tools & Dependencies
description: Installs pnpm, Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

    - name: Setup Node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24.14.0
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash
