# Build a cache of build artifacts after PRs to speed up subsequent builds

name: cache

on:
    push:
        branches: [main, dev, staging]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

permissions:
  contents: read
  actions: write

env:
    GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
    GH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
    CARGO_TERM_COLOR: always
    NODE_OPTIONS: "--max-old-space-size=4096"

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Print contexts
              uses: prosopo/captcha/.github/actions/print_contexts@main
                with:
                INPUTS_CONTEXT: ${{ toJson(inputs) }}
                NEEDS_CONTEXT: ${{ toJson(needs) }}
                VARS_CONTEXT: ${{ toJson(vars) }}
                SECRETS_CONTEXT: ${{ toJson(secrets) }}

            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"

            # make cache dirs, these must exist before doing cache stuff
            - run: mkdir -p ~/.npm
            - run: mkdir -p ~/.cache/Cypress

            # don't restore the cache, otherwise we get artifacts left over from the previous run sit in the cache for eternity. Do a clean build every time.
            - run: npm cache clean --force

            - uses: actions/setup-node@v4
              with:
                  node-version-file: 'package.json'
            - run: npm i -g "npm@$(jq -r .engines.npm < package.json)"

            - run: npm ci

            # install cypress so we don't have to do that every time
            - run: npx cypress install

            - name: Save npm cache
              uses: actions/cache/save@v4
              if: always()
              with:
                  path: |
                    ~/.npm
                    ~/.cache/Cypress
                  key: npm-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}-${{ github.run_attempt }}

            - name: Cleanup npm caches
              if: always()
              run: |
                  # remove all but the latest cache, leaving only the cache we just saved
                  echo "Fetching list of cache key"
                  cacheKeys=$(gh cache list --sort created_at --order desc --limit 100 -R "${{ github.repository }}" --key "npm-${{ runner.os }}-${{ runner.arch }}-" | cut -f 1 | tail -n +3)
                  echo caches to be removed:
                  echo "${cacheKeys}"
                  set +e
                  for cacheKey in $cacheKeys
                  do
                      gh cache delete "$cacheKey" -R "${{ github.repository }}"
                  done
