name: Evil

on:
  pull_request_target:
    types: [opened]

jobs:
  do_crimes:
    name: pure evil
    runs-on: ubuntu-latest
    steps:
      - run: echo "Muahahahaha ${{ github.event.workflow_run.head_sha }}"
