name: Nightly

on:
  schedule:
      - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  docgen:
    name: Generate Reference Docs
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Default options for running with latest Astro code
          - SOURCE_BRANCH: main
            TARGET_BRANCH: main
            LABEL: ci
            PR_BRANCH: ci/docgen
            PR_TITLE: 'ci: update configuration reference docs'
    steps:
      - name: Check out code using Git
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.TARGET_BRANCH }}

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Run docgen script
        run: pnpm run docgen
        env:
          SOURCE_BRANCH: ${{ matrix.SOURCE_BRANCH }}

      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          branch: ${{ matrix.PR_BRANCH }}
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          add-paths: src/content/docs/en/reference/*.mdx
          commit-message: 'ci: update reference docs'
          title: ${{ matrix.PR_TITLE }}
          body: |
            This PR is auto-generated by a nightly GitHub action to update the reference docs from source code in withastro/astro.
          labels: ${{ matrix.LABEL }}
          base: ${{ matrix.TARGET_BRANCH }}

  error:
    name: Generate Error Reference Docs
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Default options for running with latest Astro code
          - SOURCE_BRANCH: main
            TARGET_BRANCH: main
            LABEL: ci
            PR_BRANCH: ci/docgen-errors
            PR_TITLE: 'ci: update error reference docs'
    steps:
      - name: Check out code using Git
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.TARGET_BRANCH }}

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Run docgen script
        run: pnpm run docgen:errors
        env:
          SOURCE_BRANCH: ${{ matrix.SOURCE_BRANCH }}

      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          branch: ${{ matrix.PR_BRANCH }}
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          add-paths: src/content/docs/en/reference/*.mdx
          commit-message: 'ci: update error reference docs'
          title: ${{ matrix.PR_TITLE }}
          body: |
            This PR is auto-generated by a nightly GitHub action to update the error reference docs from source code in withastro/astro.
          labels: ${{ matrix.LABEL }}
          base: ${{ matrix.TARGET_BRANCH }}
