name: Nightly

on:
  schedule:
      - cron:  '0 12 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  docgen:
    name: Generate Reference Docs
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # TODO: switch this back to main source branch for normal operations after v7 merge!
          - SOURCE_BRANCH: 6-legacy
            TARGET_BRANCH: main
            LABEL: ci
            PR_BRANCH: ci/docgen
            PR_TITLE: 'ci: update configuration reference docs'
          # Custom options for running with Astro v7 code
          - SOURCE_BRANCH: main
            TARGET_BRANCH: v7
            LABEL: 7.0,ci
            PR_BRANCH: ci/docgen-beta
            PR_TITLE: '[BETA] ci: update reference docs'

    steps:
      - name: Check out code using Git
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ matrix.TARGET_BRANCH }}

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Run docgen script
        run: pnpm run docgen
        env:
          SOURCE_BRANCH: ${{ matrix.SOURCE_BRANCH }}

      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: ${{ matrix.PR_BRANCH }}
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          add-paths: src/content/docs/en/reference/*.mdx
          commit-message: 'ci: update reference docs'
          title: ${{ matrix.PR_TITLE }}
          body: |
            This PR is auto-generated by a nightly GitHub action to update the reference docs from source code in withastro/astro.
          labels: ${{ matrix.LABEL }}
          base: ${{ matrix.TARGET_BRANCH }}

  error:
    name: Generate Error Reference Docs
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # TODO: switch this back to main source branch for normal operations after v7 merge!
          - SOURCE_BRANCH: 6-legacy
            TARGET_BRANCH: main
            LABEL: ci
            PR_BRANCH: ci/docgen-errors
            PR_TITLE: 'ci: update error reference docs'
          # Custom options for running with Astro v7 code
          - SOURCE_BRANCH: main
            TARGET_BRANCH: v7
            LABEL: 7.0,ci
            PR_BRANCH: ci/docgen-errors-beta
            PR_TITLE: '[BETA] ci: update error reference docs'

    steps:
      - name: Check out code using Git
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ matrix.TARGET_BRANCH }}

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Run docgen script
        run: pnpm run docgen:errors
        env:
          SOURCE_BRANCH: ${{ matrix.SOURCE_BRANCH }}

      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: ${{ matrix.PR_BRANCH }}
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          add-paths: src/content/docs/en/reference/*.mdx
          commit-message: 'ci: update error reference docs'
          title: ${{ matrix.PR_TITLE }}
          body: |
            This PR is auto-generated by a nightly GitHub action to update the error reference docs from source code in withastro/astro.
          labels: ${{ matrix.LABEL }}
          base: ${{ matrix.TARGET_BRANCH }}
