name: tests

on:
  pull_request:
    branches: [main, dev, staging, release/*]
    types:
      - opened # when a PR is opened
      - synchronize # when a PR is pushed to
      - reopened # when a PR is reopened
      - ready_for_review # when a PR is marked as ready for review (e.g. taken off draft mode)
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
    GITHUB_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
    GH_TOKEN: ${{ secrets.PROSOPONATOR_PAT }}
    CARGO_TERM_COLOR: always
    NODE_OPTIONS: "--max-old-space-size=4096"
    NODE_ENV: "test"

defaults:
    run:
        shell: bash

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Print contexts
        uses: prosopo/captcha/.github/actions/print_contexts@main
          with:
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
          NEEDS_CONTEXT: ${{ toJson(needs) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - run: mkdir -p ~/.npm
      - run: mkdir -p ~/.cache/Cypress

      - name: Restore npm cache
        if: ${{ runner.environment != 'self-hosted' }} # don't restore cache on self-hosted runners, network speed not good enough
        uses: actions/cache/restore@v4
        with:
            # must restore all cache dirs, and they must exist ahead of this!
            path: |
                ~/.npm
                ~/.cache/Cypress
            # note that restoring a cache in github is a pain. The trailing '-' matches any string after the '-', therefore 'abc-' would match a cache named 'abc-1234' or 'abc-5678', etc.
            # the problem is 'abc-' will not match a cache named 'abc'! So if you're using wildcard cache name selectors like this, you need a field that changes as the suffix to become the wildcard
            # here we're setting the key to an unused cache key so it falls back to the wildcard selector in `restore-keys`
            key: some-unused-cache-key
            restore-keys: |
                npm-${{ runner.os }}-${{ runner.arch }}-

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - run: npm i -g "npm@$(jq -r .engines.npm < package.json)"

      - run: npm ci

      - run: npm run lint

      - run: npm run build
